// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: goodsservice.proto
// Original file comments:
// Copyright 2015, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote Goodss derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Inman.Platform.ServiceStub {
  /// <summary>
  ///  The greeting service definition.
  /// </summary>
  public static class GoodsService
  {
    static readonly string __ServiceName = "GoodsService";

    static readonly Marshaller<global::Inman.Platform.ServiceStub.GoodsRequest> __Marshaller_GoodsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Inman.Platform.ServiceStub.GoodsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Inman.Platform.ServiceStub.Data.Goods> __Marshaller_Goods = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Inman.Platform.ServiceStub.Data.Goods.Parser.ParseFrom);
    static readonly Marshaller<global::Inman.Platform.ServiceStub.GoodsResponse> __Marshaller_GoodsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Inman.Platform.ServiceStub.GoodsResponse.Parser.ParseFrom);

    static readonly Method<global::Inman.Platform.ServiceStub.GoodsRequest, global::Inman.Platform.ServiceStub.Data.Goods> __Method_GetGoods = new Method<global::Inman.Platform.ServiceStub.GoodsRequest, global::Inman.Platform.ServiceStub.Data.Goods>(
        MethodType.Unary,
        __ServiceName,
        "GetGoods",
        __Marshaller_GoodsRequest,
        __Marshaller_Goods);

    static readonly Method<global::Inman.Platform.ServiceStub.GoodsRequest, global::Inman.Platform.ServiceStub.GoodsResponse> __Method_GetGoodsList = new Method<global::Inman.Platform.ServiceStub.GoodsRequest, global::Inman.Platform.ServiceStub.GoodsResponse>(
        MethodType.Unary,
        __ServiceName,
        "GetGoodsList",
        __Marshaller_GoodsRequest,
        __Marshaller_GoodsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Inman.Platform.ServiceStub.GoodsserviceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GoodsService</summary>
    public abstract class GoodsServiceBase
    {
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Inman.Platform.ServiceStub.Data.Goods> GetGoods(global::Inman.Platform.ServiceStub.GoodsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Inman.Platform.ServiceStub.GoodsResponse> GetGoodsList(global::Inman.Platform.ServiceStub.GoodsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GoodsService</summary>
    public class GoodsServiceClient : ClientBase<GoodsServiceClient>
    {
      /// <summary>Creates a new client for GoodsService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GoodsServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GoodsService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GoodsServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GoodsServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GoodsServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::Inman.Platform.ServiceStub.Data.Goods GetGoods(global::Inman.Platform.ServiceStub.GoodsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetGoods(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::Inman.Platform.ServiceStub.Data.Goods GetGoods(global::Inman.Platform.ServiceStub.GoodsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetGoods, null, options, request);
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual AsyncUnaryCall<global::Inman.Platform.ServiceStub.Data.Goods> GetGoodsAsync(global::Inman.Platform.ServiceStub.GoodsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetGoodsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual AsyncUnaryCall<global::Inman.Platform.ServiceStub.Data.Goods> GetGoodsAsync(global::Inman.Platform.ServiceStub.GoodsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetGoods, null, options, request);
      }
      public virtual global::Inman.Platform.ServiceStub.GoodsResponse GetGoodsList(global::Inman.Platform.ServiceStub.GoodsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetGoodsList(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Inman.Platform.ServiceStub.GoodsResponse GetGoodsList(global::Inman.Platform.ServiceStub.GoodsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetGoodsList, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Inman.Platform.ServiceStub.GoodsResponse> GetGoodsListAsync(global::Inman.Platform.ServiceStub.GoodsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetGoodsListAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Inman.Platform.ServiceStub.GoodsResponse> GetGoodsListAsync(global::Inman.Platform.ServiceStub.GoodsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetGoodsList, null, options, request);
      }
      protected override GoodsServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GoodsServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(GoodsServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetGoods, serviceImpl.GetGoods)
          .AddMethod(__Method_GetGoodsList, serviceImpl.GetGoodsList).Build();
    }

  }
}
#endregion
