// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockitemservice.proto
// Original file comments:
// Copyright 2015, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Inman.Platform.ServiceStub {
  /// <summary>
  ///  The greeting service definition.
  /// </summary>
  public static class StockItemService
  {
    static readonly string __ServiceName = "StockItemService";

    static readonly Marshaller<global::Inman.Platform.ServiceStub.StockItemRequest> __Marshaller_StockItemRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Inman.Platform.ServiceStub.StockItemRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Inman.Platform.ServiceStub.Data.StockItem> __Marshaller_StockItem = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Inman.Platform.ServiceStub.Data.StockItem.Parser.ParseFrom);
    static readonly Marshaller<global::Inman.Platform.ServiceStub.StockItemResponse> __Marshaller_StockItemResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Inman.Platform.ServiceStub.StockItemResponse.Parser.ParseFrom);

    static readonly Method<global::Inman.Platform.ServiceStub.StockItemRequest, global::Inman.Platform.ServiceStub.Data.StockItem> __Method_GetStockItem = new Method<global::Inman.Platform.ServiceStub.StockItemRequest, global::Inman.Platform.ServiceStub.Data.StockItem>(
        MethodType.Unary,
        __ServiceName,
        "GetStockItem",
        __Marshaller_StockItemRequest,
        __Marshaller_StockItem);

    static readonly Method<global::Inman.Platform.ServiceStub.StockItemRequest, global::Inman.Platform.ServiceStub.StockItemResponse> __Method_GetStockItemList = new Method<global::Inman.Platform.ServiceStub.StockItemRequest, global::Inman.Platform.ServiceStub.StockItemResponse>(
        MethodType.Unary,
        __ServiceName,
        "GetStockItemList",
        __Marshaller_StockItemRequest,
        __Marshaller_StockItemResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Inman.Platform.ServiceStub.StockitemserviceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of StockItemService</summary>
    public abstract class StockItemServiceBase
    {
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Inman.Platform.ServiceStub.Data.StockItem> GetStockItem(global::Inman.Platform.ServiceStub.StockItemRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Inman.Platform.ServiceStub.StockItemResponse> GetStockItemList(global::Inman.Platform.ServiceStub.StockItemRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for StockItemService</summary>
    public class StockItemServiceClient : ClientBase<StockItemServiceClient>
    {
      /// <summary>Creates a new client for StockItemService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public StockItemServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for StockItemService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public StockItemServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected StockItemServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected StockItemServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::Inman.Platform.ServiceStub.Data.StockItem GetStockItem(global::Inman.Platform.ServiceStub.StockItemRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetStockItem(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::Inman.Platform.ServiceStub.Data.StockItem GetStockItem(global::Inman.Platform.ServiceStub.StockItemRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetStockItem, null, options, request);
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual AsyncUnaryCall<global::Inman.Platform.ServiceStub.Data.StockItem> GetStockItemAsync(global::Inman.Platform.ServiceStub.StockItemRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetStockItemAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual AsyncUnaryCall<global::Inman.Platform.ServiceStub.Data.StockItem> GetStockItemAsync(global::Inman.Platform.ServiceStub.StockItemRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetStockItem, null, options, request);
      }
      public virtual global::Inman.Platform.ServiceStub.StockItemResponse GetStockItemList(global::Inman.Platform.ServiceStub.StockItemRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetStockItemList(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Inman.Platform.ServiceStub.StockItemResponse GetStockItemList(global::Inman.Platform.ServiceStub.StockItemRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetStockItemList, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Inman.Platform.ServiceStub.StockItemResponse> GetStockItemListAsync(global::Inman.Platform.ServiceStub.StockItemRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetStockItemListAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Inman.Platform.ServiceStub.StockItemResponse> GetStockItemListAsync(global::Inman.Platform.ServiceStub.StockItemRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetStockItemList, null, options, request);
      }
      protected override StockItemServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new StockItemServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(StockItemServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetStockItem, serviceImpl.GetStockItem)
          .AddMethod(__Method_GetStockItemList, serviceImpl.GetStockItemList).Build();
    }

  }
}
#endregion
